### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by 2653888596** [pjessesco/grundhofer2015#1]
Thank you very much for your work. I would like to ask what data set is your data set used? 
We should only use one ref map, right? 
Currently I am using the data set made by the author of Compennet, but there are 126 shadings,
 but only 500 captured photos of one of the shadings, but I input your code and it shows an error.
Looking forward to your reply ！

**Comment by pjessesco** [comment]
Hi,

https://github.com/pjessesco/grundhofer2015/blob/53630473176ea09e9f13dd1aa3feb96025265a32/tps_color_transform.py#L37

N is a number of image pairs (projector input, camera-captured output). I set it 125 to use colored dataset (`ref` directory), or 500 to use textured dataset (`train` dir). 

Could you share your error message?

**Comment by 2653888596** [comment]
Thank you very much for your prompt reply! 

It seems that I am confused about the concept, N stands for image pair（projector input, camera-captured output） .

TPS method process image alignment does not involve ref ?
It means that if I use the data set in the train folder, I only need the projector input to represent ref, and captured represents the image captured by the camera in the train folder, is that right? 

Thank you ！

**Comment by pjessesco** [comment]
TPS method assumes that its input images (projector input, camera-captured output) are in the same image space, it does not perform any warping or aligning.

If you're using CompenNet dataset, IIRC camera-captured images are already aligned to ref (desired) images.

But if you made your own dataset from CompenNet author's projector input images (i.e., if you captured image by yourself), I think you have to warp them manually.

**Comment by 2653888596** [comment]
I admire your work very much!

I understand what you mean. If we make the data set ourselves, 
we will do what you say. 

Thank you very much for your help~

**Comment by pjessesco** [comment]
I'm glad to help you 😃
